version: "2.1"

services:
  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - "7894:80"
    volumes:
      - ./public:/usr/share/nginx/html/dist
      - ./nginx.conf:/etc/nginx/nginx.conf
# docker-compose up -d
